/**
 * 統一錯誤代碼管理
 * 
 * 定義專案中所有使用的錯誤代碼，確保：
 * 1. 錯誤代碼命名一致且語義清楚
 * 2. 避免重複定義相同功能的錯誤代碼
 * 3. 便於統一維護和查找
 * 4. 與 HTTP 狀態碼對應
 */

export const ERROR_CODES = {
  // === 認證相關錯誤代碼 ===
  // 帳號認證
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  NICKNAME_EXISTS: 'NICKNAME_EXISTS', 
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  
  // Token 相關
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REQUIRED: 'TOKEN_REQUIRED',
  TOKEN_INVALID_OR_EXPIRED: 'TOKEN_INVALID_OR_EXPIRED',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  ACCOUNT_SUSPENDED_RESET: 'ACCOUNT_SUSPENDED_RESET',

  // === 驗證相關錯誤代碼 ===
  // 基本驗證
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  FIELD_INVALID_TYPE: 'FIELD_INVALID_TYPE',
  
  // Email 驗證
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  EMAIL_INVALID: 'EMAIL_INVALID',
  EMAIL_EMPTY: 'EMAIL_EMPTY',
  
  // 密碼驗證
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  PASSWORD_EMPTY: 'PASSWORD_EMPTY',
  NEW_PASSWORD_REQUIRED: 'NEW_PASSWORD_REQUIRED',
  NEW_PASSWORD_EMPTY: 'NEW_PASSWORD_EMPTY',
  NEW_PASSWORD_TOO_SHORT: 'NEW_PASSWORD_TOO_SHORT',
  NEW_PASSWORD_INVALID_TYPE: 'NEW_PASSWORD_INVALID_TYPE',
  
  // 暱稱驗證
  NICKNAME_REQUIRED: 'NICKNAME_REQUIRED',
  NICKNAME_EMPTY: 'NICKNAME_EMPTY',
  NICKNAME_TOO_LONG: 'NICKNAME_TOO_LONG',
  
  // Token 驗證
  RESET_TOKEN_REQUIRED: 'RESET_TOKEN_REQUIRED',
  RESET_TOKEN_EMPTY: 'RESET_TOKEN_EMPTY',
  REFRESH_TOKEN_EMPTY: 'REFRESH_TOKEN_EMPTY',
  REFRESH_TOKEN_INVALID_TYPE: 'REFRESH_TOKEN_INVALID_TYPE',
  
  // 工作經驗驗證
  WORKPLACE_REQUIRED: 'WORKPLACE_REQUIRED',
  END_DATE_BEFORE_START_DATE: 'END_DATE_BEFORE_START_DATE',
  WORKING_END_DATE_NOT_ALLOWED: 'WORKING_END_DATE_NOT_ALLOWED',
  NON_WORKING_END_DATE_REQUIRED: 'NON_WORKING_END_DATE_REQUIRED',
  
  // 學習經歷驗證
  INSTITUTION_REQUIRED: 'INSTITUTION_REQUIRED',
  INSTITUTION_EMPTY: 'INSTITUTION_EMPTY',
  DEGREE_REQUIRED: 'DEGREE_REQUIRED',
  DEGREE_EMPTY: 'DEGREE_EMPTY',
  FIELD_OF_STUDY_REQUIRED: 'FIELD_OF_STUDY_REQUIRED',
  FIELD_OF_STUDY_EMPTY: 'FIELD_OF_STUDY_EMPTY',
  START_YEAR_REQUIRED: 'START_YEAR_REQUIRED',
  START_YEAR_INVALID: 'START_YEAR_INVALID',
  END_YEAR_REQUIRED: 'END_YEAR_REQUIRED',
  END_YEAR_INVALID: 'END_YEAR_INVALID',
  LEARNING_END_YEAR_BEFORE_START_YEAR: 'LEARNING_END_YEAR_BEFORE_START_YEAR',
  LEARNING_YEAR_RANGE_INVALID: 'LEARNING_YEAR_RANGE_INVALID',
  LEARNING_GRADUATED_NO_END_DATE: 'LEARNING_GRADUATED_NO_END_DATE',
  
  // 課程驗證
  COURSE_NAME_REQUIRED: 'COURSE_NAME_REQUIRED',
  COURSE_NAME_TOO_LONG: 'COURSE_NAME_TOO_LONG',
  COURSE_CONTENT_REQUIRED: 'COURSE_CONTENT_REQUIRED',
  COURSE_CONTENT_TOO_LONG: 'COURSE_CONTENT_TOO_LONG',
  MAIN_CATEGORY_REQUIRED: 'MAIN_CATEGORY_REQUIRED',
  MAIN_CATEGORY_INVALID: 'MAIN_CATEGORY_INVALID',
  SUB_CATEGORY_REQUIRED: 'SUB_CATEGORY_REQUIRED',
  SUB_CATEGORY_INVALID: 'SUB_CATEGORY_INVALID',
  CITY_REQUIRED: 'CITY_REQUIRED',
  CITY_INVALID: 'CITY_INVALID',
  SURVEY_URL_INVALID: 'SURVEY_URL_INVALID',
  PURCHASE_MESSAGE_TOO_LONG: 'PURCHASE_MESSAGE_TOO_LONG',

  // 價格方案驗證
  PRICE_REQUIRED: 'PRICE_REQUIRED',
  PRICE_INVALID: 'PRICE_INVALID',
  PRICE_TOO_LOW: 'PRICE_TOO_LOW',
  PRICE_TOO_HIGH: 'PRICE_TOO_HIGH',
  QUANTITY_REQUIRED: 'QUANTITY_REQUIRED',
  QUANTITY_INVALID: 'QUANTITY_INVALID',
  QUANTITY_TOO_LOW: 'QUANTITY_TOO_LOW',
  QUANTITY_TOO_HIGH: 'QUANTITY_TOO_HIGH',

  // 影片驗證
  VIDEO_NAME_REQUIRED: 'VIDEO_NAME_REQUIRED',
  VIDEO_NAME_EMPTY: 'VIDEO_NAME_EMPTY',
  VIDEO_NAME_TOO_LONG: 'VIDEO_NAME_TOO_LONG',
  VIDEO_CATEGORY_REQUIRED: 'VIDEO_CATEGORY_REQUIRED',
  VIDEO_CATEGORY_EMPTY: 'VIDEO_CATEGORY_EMPTY',
  VIDEO_CATEGORY_TOO_LONG: 'VIDEO_CATEGORY_TOO_LONG',
  VIDEO_INTRO_REQUIRED: 'VIDEO_INTRO_REQUIRED',
  VIDEO_INTRO_EMPTY: 'VIDEO_INTRO_EMPTY',
  VIDEO_INTRO_TOO_LONG: 'VIDEO_INTRO_TOO_LONG',
  VIDEO_TYPE_REQUIRED: 'VIDEO_TYPE_REQUIRED',
  VIDEO_TYPE_INVALID: 'VIDEO_TYPE_INVALID',
  VIDEO_FILE_REQUIRED: 'VIDEO_FILE_REQUIRED',
  VIDEO_FILE_TOO_LARGE: 'VIDEO_FILE_TOO_LARGE',
  VIDEO_FILE_FORMAT_INVALID: 'VIDEO_FILE_FORMAT_INVALID',
  YOUTUBE_URL_REQUIRED: 'YOUTUBE_URL_REQUIRED',
  YOUTUBE_URL_INVALID: 'YOUTUBE_URL_INVALID',
  THUMBNAIL_FILE_TOO_LARGE: 'THUMBNAIL_FILE_TOO_LARGE',
  THUMBNAIL_FILE_FORMAT_INVALID: 'THUMBNAIL_FILE_FORMAT_INVALID',

  // 課程影片關聯驗證
  VIDEO_IDS_REQUIRED: 'VIDEO_IDS_REQUIRED',
  VIDEO_IDS_EMPTY: 'VIDEO_IDS_EMPTY',
  VIDEO_IDS_INVALID: 'VIDEO_IDS_INVALID',
  VIDEO_ID_INVALID: 'VIDEO_ID_INVALID',
  VIDEO_ORDERS_REQUIRED: 'VIDEO_ORDERS_REQUIRED',
  VIDEO_ORDERS_EMPTY: 'VIDEO_ORDERS_EMPTY',
  VIDEO_ORDERS_INVALID: 'VIDEO_ORDERS_INVALID',
  DISPLAY_ORDER_REQUIRED: 'DISPLAY_ORDER_REQUIRED',
  DISPLAY_ORDER_INVALID: 'DISPLAY_ORDER_INVALID',
  IS_PREVIEW_INVALID: 'IS_PREVIEW_INVALID',

  // 課程檔案驗證
  COURSE_FILES_REQUIRED: 'COURSE_FILES_REQUIRED',
  COURSE_FILES_EMPTY: 'COURSE_FILES_EMPTY',
  COURSE_FILE_TOO_LARGE: 'COURSE_FILE_TOO_LARGE',
  COURSE_FILE_FORMAT_INVALID: 'COURSE_FILE_FORMAT_INVALID',
  COURSE_FILE_COUNT_EXCEEDED: 'COURSE_FILE_COUNT_EXCEEDED',
  COURSE_FILE_UPLOAD_LIMIT_EXCEEDED: 'COURSE_FILE_UPLOAD_LIMIT_EXCEEDED',
  COURSE_FILE_NAME_REQUIRED: 'COURSE_FILE_NAME_REQUIRED',
  COURSE_FILE_NAME_TOO_LONG: 'COURSE_FILE_NAME_TOO_LONG',

  // === 業務邏輯錯誤代碼 ===
  // 資源不存在
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  WORK_EXPERIENCE_NOT_FOUND: 'WORK_EXPERIENCE_NOT_FOUND',
  WORK_EXPERIENCE_RECORD_NOT_FOUND: 'WORK_EXPERIENCE_RECORD_NOT_FOUND',
  LEARNING_EXPERIENCE_NOT_FOUND: 'LEARNING_EXPERIENCE_NOT_FOUND',
  LEARNING_EXPERIENCE_RECORD_NOT_FOUND: 'LEARNING_EXPERIENCE_RECORD_NOT_FOUND',
  PRICE_OPTION_NOT_FOUND: 'PRICE_OPTION_NOT_FOUND',
  VIDEO_NOT_FOUND: 'VIDEO_NOT_FOUND',
  COURSE_VIDEO_NOT_FOUND: 'COURSE_VIDEO_NOT_FOUND',
  COURSE_FILE_NOT_FOUND: 'COURSE_FILE_NOT_FOUND',
  
  // 業務規則違反
  APPLICATION_EXISTS: 'APPLICATION_EXISTS',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  UNAUTHORIZED_WORK_EXPERIENCE_ACCESS: 'UNAUTHORIZED_WORK_EXPERIENCE_ACCESS',
  UNAUTHORIZED_WORK_EXPERIENCE_DELETE: 'UNAUTHORIZED_WORK_EXPERIENCE_DELETE',
  UNAUTHORIZED_LEARNING_EXPERIENCE_ACCESS: 'UNAUTHORIZED_LEARNING_EXPERIENCE_ACCESS',
  UNAUTHORIZED_LEARNING_EXPERIENCE_DELETE: 'UNAUTHORIZED_LEARNING_EXPERIENCE_DELETE',
  TEACHER_PERMISSION_REQUIRED: 'TEACHER_PERMISSION_REQUIRED',
  STUDENT_ONLY_APPLY_TEACHER: 'STUDENT_ONLY_APPLY_TEACHER',
  ACCOUNT_STATUS_INVALID: 'ACCOUNT_STATUS_INVALID',
  APPLICATION_STATUS_INVALID: 'APPLICATION_STATUS_INVALID',
  TEACHER_NOT_APPROVED: 'TEACHER_NOT_APPROVED',
  COURSE_NOT_DRAFT: 'COURSE_NOT_DRAFT',
  COURSE_NOT_APPROVED: 'COURSE_NOT_APPROVED',
  COURSE_ALREADY_PUBLISHED: 'COURSE_ALREADY_PUBLISHED',
  COURSE_CANNOT_SUBMIT: 'COURSE_CANNOT_SUBMIT',
  COURSE_CANNOT_RESUBMIT: 'COURSE_CANNOT_RESUBMIT',
  COURSE_CANNOT_PUBLISH: 'COURSE_CANNOT_PUBLISH',
  COURSE_CANNOT_ARCHIVE: 'COURSE_CANNOT_ARCHIVE',
  COURSE_UNDER_REVIEW: 'COURSE_UNDER_REVIEW',
  
  // 價格方案業務規則
  PRICE_OPTION_DUPLICATE: 'PRICE_OPTION_DUPLICATE',
  PRICE_OPTION_LIMIT_EXCEEDED: 'PRICE_OPTION_LIMIT_EXCEEDED',
  PRICE_OPTION_LAST_ONE: 'PRICE_OPTION_LAST_ONE',
  PRICE_OPTION_HAS_PURCHASES: 'PRICE_OPTION_HAS_PURCHASES',
  
  // 影片業務規則
  VIDEO_PERMISSION_REQUIRED: 'VIDEO_PERMISSION_REQUIRED',
  VIDEO_IN_USE: 'VIDEO_IN_USE',
  VIDEO_CANNOT_DELETE: 'VIDEO_CANNOT_DELETE',
  VIDEO_UPLOAD_FAILED: 'VIDEO_UPLOAD_FAILED',
  VIDEO_PROCESSING_FAILED: 'VIDEO_PROCESSING_FAILED',
  
  // 課程影片關聯業務規則
  COURSE_VIDEO_ALREADY_LINKED: 'COURSE_VIDEO_ALREADY_LINKED',
  COURSE_VIDEO_NOT_LINKED: 'COURSE_VIDEO_NOT_LINKED',
  VIDEO_NOT_OWNED_BY_TEACHER: 'VIDEO_NOT_OWNED_BY_TEACHER',
  COURSE_VIDEO_DUPLICATE_ORDER: 'COURSE_VIDEO_DUPLICATE_ORDER',
  COURSE_VIDEO_MISSING_VIDEOS: 'COURSE_VIDEO_MISSING_VIDEOS',
  COURSE_VIDEO_INVALID_ORDER: 'COURSE_VIDEO_INVALID_ORDER',
  
  // 課程檔案業務規則
  COURSE_FILE_PERMISSION_REQUIRED: 'COURSE_FILE_PERMISSION_REQUIRED',
  COURSE_FILE_UPLOAD_FAILED: 'COURSE_FILE_UPLOAD_FAILED',
  COURSE_FILE_DELETE_FAILED: 'COURSE_FILE_DELETE_FAILED',
  COURSE_FILE_LIMIT_REACHED: 'COURSE_FILE_LIMIT_REACHED',
  
  // 操作失敗
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
  COURSE_PUBLISHED_CANNOT_DELETE: 'COURSE_PUBLISHED_CANNOT_DELETE',

  // === 系統錯誤代碼 ===
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  TEACHER_APPLICATION_VALIDATION_FAILED: 'TEACHER_APPLICATION_VALIDATION_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const

// 錯誤代碼分類對照
export const ERROR_CODE_CATEGORIES = {
  // 認證相關 (401, 403)
  AUTH: [
    ERROR_CODES.EMAIL_EXISTS,
    ERROR_CODES.NICKNAME_EXISTS,
    ERROR_CODES.INVALID_CREDENTIALS,
    ERROR_CODES.ACCOUNT_SUSPENDED,
    ERROR_CODES.TOKEN_INVALID,
    ERROR_CODES.TOKEN_EXPIRED,
    ERROR_CODES.TOKEN_REQUIRED,
    ERROR_CODES.TOKEN_INVALID_OR_EXPIRED,
    ERROR_CODES.REFRESH_TOKEN_REQUIRED,
    ERROR_CODES.RESET_TOKEN_INVALID,
    ERROR_CODES.ACCOUNT_SUSPENDED_RESET,
  ],

  // 驗證相關 (400)
  VALIDATION: [
    ERROR_CODES.VALIDATION_ERROR,
    ERROR_CODES.FIELD_REQUIRED,
    ERROR_CODES.FIELD_INVALID_TYPE,
    ERROR_CODES.EMAIL_REQUIRED,
    ERROR_CODES.EMAIL_INVALID,
    ERROR_CODES.EMAIL_EMPTY,
    ERROR_CODES.PASSWORD_REQUIRED,
    ERROR_CODES.PASSWORD_TOO_SHORT,
    ERROR_CODES.PASSWORD_EMPTY,
    ERROR_CODES.NEW_PASSWORD_REQUIRED,
    ERROR_CODES.NEW_PASSWORD_EMPTY,
    ERROR_CODES.NEW_PASSWORD_TOO_SHORT,
    ERROR_CODES.NEW_PASSWORD_INVALID_TYPE,
    ERROR_CODES.NICKNAME_REQUIRED,
    ERROR_CODES.NICKNAME_EMPTY,
    ERROR_CODES.NICKNAME_TOO_LONG,
    ERROR_CODES.RESET_TOKEN_REQUIRED,
    ERROR_CODES.RESET_TOKEN_EMPTY,
    ERROR_CODES.REFRESH_TOKEN_EMPTY,
    ERROR_CODES.REFRESH_TOKEN_INVALID_TYPE,
    ERROR_CODES.WORKPLACE_REQUIRED,
    ERROR_CODES.END_DATE_BEFORE_START_DATE,
    ERROR_CODES.WORKING_END_DATE_NOT_ALLOWED,
    ERROR_CODES.NON_WORKING_END_DATE_REQUIRED,
    ERROR_CODES.INSTITUTION_REQUIRED,
    ERROR_CODES.INSTITUTION_EMPTY,
    ERROR_CODES.DEGREE_REQUIRED,
    ERROR_CODES.DEGREE_EMPTY,
    ERROR_CODES.FIELD_OF_STUDY_REQUIRED,
    ERROR_CODES.FIELD_OF_STUDY_EMPTY,
    ERROR_CODES.START_YEAR_REQUIRED,
    ERROR_CODES.START_YEAR_INVALID,
    ERROR_CODES.END_YEAR_REQUIRED,
    ERROR_CODES.END_YEAR_INVALID,
    ERROR_CODES.LEARNING_END_YEAR_BEFORE_START_YEAR,
    ERROR_CODES.LEARNING_YEAR_RANGE_INVALID,
    ERROR_CODES.LEARNING_GRADUATED_NO_END_DATE,
    ERROR_CODES.COURSE_NAME_REQUIRED,
    ERROR_CODES.COURSE_NAME_TOO_LONG,
    ERROR_CODES.COURSE_CONTENT_REQUIRED,
    ERROR_CODES.COURSE_CONTENT_TOO_LONG,
    ERROR_CODES.MAIN_CATEGORY_REQUIRED,
    ERROR_CODES.MAIN_CATEGORY_INVALID,
    ERROR_CODES.SUB_CATEGORY_REQUIRED,
    ERROR_CODES.SUB_CATEGORY_INVALID,
    ERROR_CODES.CITY_REQUIRED,
    ERROR_CODES.CITY_INVALID,
    ERROR_CODES.SURVEY_URL_INVALID,
    ERROR_CODES.PURCHASE_MESSAGE_TOO_LONG,
    ERROR_CODES.PRICE_REQUIRED,
    ERROR_CODES.PRICE_INVALID,
    ERROR_CODES.PRICE_TOO_LOW,
    ERROR_CODES.PRICE_TOO_HIGH,
    ERROR_CODES.QUANTITY_REQUIRED,
    ERROR_CODES.QUANTITY_INVALID,
    ERROR_CODES.QUANTITY_TOO_LOW,
    ERROR_CODES.QUANTITY_TOO_HIGH,
    ERROR_CODES.VIDEO_NAME_REQUIRED,
    ERROR_CODES.VIDEO_NAME_EMPTY,
    ERROR_CODES.VIDEO_NAME_TOO_LONG,
    ERROR_CODES.VIDEO_CATEGORY_REQUIRED,
    ERROR_CODES.VIDEO_CATEGORY_EMPTY,
    ERROR_CODES.VIDEO_CATEGORY_TOO_LONG,
    ERROR_CODES.VIDEO_INTRO_REQUIRED,
    ERROR_CODES.VIDEO_INTRO_EMPTY,
    ERROR_CODES.VIDEO_INTRO_TOO_LONG,
    ERROR_CODES.VIDEO_TYPE_REQUIRED,
    ERROR_CODES.VIDEO_TYPE_INVALID,
    ERROR_CODES.VIDEO_FILE_REQUIRED,
    ERROR_CODES.VIDEO_FILE_TOO_LARGE,
    ERROR_CODES.VIDEO_FILE_FORMAT_INVALID,
    ERROR_CODES.YOUTUBE_URL_REQUIRED,
    ERROR_CODES.YOUTUBE_URL_INVALID,
    ERROR_CODES.THUMBNAIL_FILE_TOO_LARGE,
    ERROR_CODES.THUMBNAIL_FILE_FORMAT_INVALID,
    ERROR_CODES.VIDEO_IDS_REQUIRED,
    ERROR_CODES.VIDEO_IDS_EMPTY,
    ERROR_CODES.VIDEO_IDS_INVALID,
    ERROR_CODES.VIDEO_ID_INVALID,
    ERROR_CODES.VIDEO_ORDERS_REQUIRED,
    ERROR_CODES.VIDEO_ORDERS_EMPTY,
    ERROR_CODES.VIDEO_ORDERS_INVALID,
    ERROR_CODES.DISPLAY_ORDER_REQUIRED,
    ERROR_CODES.DISPLAY_ORDER_INVALID,
    ERROR_CODES.IS_PREVIEW_INVALID,
    ERROR_CODES.COURSE_FILES_REQUIRED,
    ERROR_CODES.COURSE_FILES_EMPTY,
    ERROR_CODES.COURSE_FILE_TOO_LARGE,
    ERROR_CODES.COURSE_FILE_FORMAT_INVALID,
    ERROR_CODES.COURSE_FILE_COUNT_EXCEEDED,
    ERROR_CODES.COURSE_FILE_UPLOAD_LIMIT_EXCEEDED,
    ERROR_CODES.COURSE_FILE_NAME_REQUIRED,
    ERROR_CODES.COURSE_FILE_NAME_TOO_LONG,
  ],

  // 資源不存在 (404)
  NOT_FOUND: [
    ERROR_CODES.USER_NOT_FOUND,
    ERROR_CODES.TEACHER_NOT_FOUND,
    ERROR_CODES.COURSE_NOT_FOUND,
    ERROR_CODES.APPLICATION_NOT_FOUND,
    ERROR_CODES.WORK_EXPERIENCE_NOT_FOUND,
    ERROR_CODES.WORK_EXPERIENCE_RECORD_NOT_FOUND,
    ERROR_CODES.LEARNING_EXPERIENCE_NOT_FOUND,
    ERROR_CODES.LEARNING_EXPERIENCE_RECORD_NOT_FOUND,
    ERROR_CODES.PRICE_OPTION_NOT_FOUND,
    ERROR_CODES.VIDEO_NOT_FOUND,
    ERROR_CODES.COURSE_VIDEO_NOT_FOUND,
    ERROR_CODES.COURSE_FILE_NOT_FOUND,
  ],

  // 業務規則違反 (409, 403, 422)
  BUSINESS: [
    ERROR_CODES.APPLICATION_EXISTS,
    ERROR_CODES.UNAUTHORIZED_ACCESS,
    ERROR_CODES.UNAUTHORIZED_WORK_EXPERIENCE_ACCESS,
    ERROR_CODES.UNAUTHORIZED_WORK_EXPERIENCE_DELETE,
    ERROR_CODES.UNAUTHORIZED_LEARNING_EXPERIENCE_ACCESS,
    ERROR_CODES.UNAUTHORIZED_LEARNING_EXPERIENCE_DELETE,
    ERROR_CODES.TEACHER_PERMISSION_REQUIRED,
    ERROR_CODES.STUDENT_ONLY_APPLY_TEACHER,
    ERROR_CODES.ACCOUNT_STATUS_INVALID,
    ERROR_CODES.APPLICATION_STATUS_INVALID,
    ERROR_CODES.TEACHER_NOT_APPROVED,
    ERROR_CODES.COURSE_NOT_DRAFT,
    ERROR_CODES.COURSE_NOT_APPROVED,
    ERROR_CODES.COURSE_ALREADY_PUBLISHED,
    ERROR_CODES.COURSE_CANNOT_SUBMIT,
    ERROR_CODES.COURSE_CANNOT_RESUBMIT,
    ERROR_CODES.COURSE_CANNOT_PUBLISH,
    ERROR_CODES.COURSE_CANNOT_ARCHIVE,
    ERROR_CODES.COURSE_UNDER_REVIEW,
    ERROR_CODES.REGISTRATION_FAILED,
    ERROR_CODES.LOGIN_FAILED,
    ERROR_CODES.PROFILE_UPDATE_FAILED,
    ERROR_CODES.PASSWORD_RESET_FAILED,
    ERROR_CODES.TOKEN_REFRESH_FAILED,
    ERROR_CODES.COURSE_PUBLISHED_CANNOT_DELETE,
    ERROR_CODES.PRICE_OPTION_DUPLICATE,
    ERROR_CODES.PRICE_OPTION_LIMIT_EXCEEDED,
    ERROR_CODES.PRICE_OPTION_LAST_ONE,
    ERROR_CODES.PRICE_OPTION_HAS_PURCHASES,
    ERROR_CODES.VIDEO_PERMISSION_REQUIRED,
    ERROR_CODES.VIDEO_IN_USE,
    ERROR_CODES.VIDEO_CANNOT_DELETE,
    ERROR_CODES.VIDEO_UPLOAD_FAILED,
    ERROR_CODES.VIDEO_PROCESSING_FAILED,
    ERROR_CODES.COURSE_VIDEO_ALREADY_LINKED,
    ERROR_CODES.COURSE_VIDEO_NOT_LINKED,
    ERROR_CODES.VIDEO_NOT_OWNED_BY_TEACHER,
    ERROR_CODES.COURSE_VIDEO_DUPLICATE_ORDER,
    ERROR_CODES.COURSE_VIDEO_MISSING_VIDEOS,
    ERROR_CODES.COURSE_VIDEO_INVALID_ORDER,
    ERROR_CODES.COURSE_FILE_PERMISSION_REQUIRED,
    ERROR_CODES.COURSE_FILE_UPLOAD_FAILED,
    ERROR_CODES.COURSE_FILE_DELETE_FAILED,
    ERROR_CODES.COURSE_FILE_LIMIT_REACHED,
  ],

  // 系統錯誤 (500)
  SYSTEM: [
    ERROR_CODES.INTERNAL_ERROR,
    ERROR_CODES.DATABASE_ERROR,
    ERROR_CODES.VALIDATION_FAILED,
    ERROR_CODES.TEACHER_APPLICATION_VALIDATION_FAILED,
    ERROR_CODES.UNKNOWN_ERROR,
  ],
} as const

// 型別定義
export type ErrorCode = keyof typeof ERROR_CODES
export type ErrorCodeValue = typeof ERROR_CODES[keyof typeof ERROR_CODES]
export type ErrorCategory = keyof typeof ERROR_CODE_CATEGORIES

// 工具函式：根據錯誤代碼取得分類
export const getErrorCategory = (errorCode: string): ErrorCategory | null => {
  for (const [category, codes] of Object.entries(ERROR_CODE_CATEGORIES)) {
    if ((codes as readonly string[]).includes(errorCode)) {
      return category as ErrorCategory
    }
  }
  return null
}

// 工具函式：檢查錯誤代碼是否存在
export const isValidErrorCode = (code: string): code is ErrorCodeValue => {
  return Object.values(ERROR_CODES).includes(code as ErrorCodeValue)
}