/**
 * 統一訊息管理
 * 
 * 管理專案中所有的成功與失敗回應訊息，用於：
 * 1. Controllers 控制器回應訊息
 * 2. Services 服務層拋錯訊息  
 * 3. Tests 測試案例預期訊息
 * 4. Routes 路由驗證訊息
 * 
 * 確保整個專案使用統一的訊息格式
 */

export const MESSAGES = {
  // === 認證相關訊息 ===
  AUTH: {
    // 成功訊息
    REGISTRATION_SUCCESS: '註冊成功',
    LOGIN_SUCCESS: '登入成功',
    TOKEN_REFRESH_SUCCESS: 'Token 刷新成功',
    PASSWORD_RESET_EMAIL_SENT: '重設密碼郵件已發送，請檢查您的信箱',
    PASSWORD_RESET_SUCCESS: '密碼重設成功',
    PROFILE_RETRIEVED: '成功取得個人資料',
    PROFILE_UPDATED: '成功更新個人資料',
    ACCOUNT_DELETED: '帳號已成功刪除',
    AVATAR_UPLOADED: '頭像上傳成功',
    AVATAR_UPDATED: '頭像更新成功',
    AVATAR_DELETED: '頭像刪除成功',

    // 管理員成功訊息
    ADMIN_LOGIN_SUCCESS: '管理員登入成功',
    ADMIN_LOGOUT_SUCCESS: '管理員登出成功',
    ADMIN_CREATED_SUCCESS: '管理員帳號建立成功',

    // 錯誤訊息
    EMAIL_EXISTS: '此電子郵件已被註冊',
    NICKNAME_EXISTS: '該暱稱已被使用',
    INVALID_CREDENTIALS: '電子郵件或密碼錯誤',
    ACCOUNT_SUSPENDED: '您的帳號已被停用，請聯絡客服',
    TOKEN_INVALID: 'Token 無效',
    TOKEN_EXPIRED: 'Token 已過期',
    TOKEN_REQUIRED: 'Access token 為必填欄位',
    TOKEN_INVALID_OR_EXPIRED: 'Token 無效或已過期',
    REFRESH_TOKEN_REQUIRED: 'Refresh token 為必填欄位',
    RESET_TOKEN_INVALID: '重設令牌無效或已過期',
    ACCOUNT_SUSPENDED_RESET: '帳號已停用，無法重設密碼',
    REGISTRATION_FAILED: '註冊失敗',
    LOGIN_FAILED: '登入失敗',
    PROFILE_UPDATE_FAILED: '更新個人資料失敗',
    PASSWORD_RESET_FAILED: '密碼重設失敗',
    TOKEN_REFRESH_FAILED: 'Token 刷新失敗',

    // 管理員錯誤訊息
    ADMIN_INVALID_CREDENTIALS: '管理員帳號或密碼錯誤',
    ADMIN_ACCOUNT_INACTIVE: '管理員帳號已停用，請聯絡系統管理員',
    ADMIN_LOGIN_FAILED: '管理員登入失敗，請重試',
    ADMIN_TOKEN_REQUIRED: '管理員 token 為必填欄位',
    ADMIN_TOKEN_INVALID: '管理員 token 無效',
    ADMIN_PERMISSION_DENIED: '沒有管理員權限',
  },

  // === 驗證相關訊息 ===
  VALIDATION: {
    // Email 驗證
    EMAIL_REQUIRED: 'Email 為必填欄位',
    EMAIL_INVALID: 'Email 格式不正確',
    EMAIL_EMPTY: 'Email 不能為空',

    // 密碼驗證
    PASSWORD_REQUIRED: '密碼為必填欄位',
    PASSWORD_TOO_SHORT: '密碼必須至少8字元且包含中英文',
    PASSWORD_EMPTY: '密碼不能為空',
    NEW_PASSWORD_REQUIRED: '新密碼為必填欄位',
    NEW_PASSWORD_EMPTY: '新密碼不能為空',
    NEW_PASSWORD_TOO_SHORT: '密碼至少需要 8 個字元',
    NEW_PASSWORD_INVALID_TYPE: '新密碼必須為字串格式',

    // 暱稱驗證
    NICKNAME_REQUIRED: '暱稱為必填欄位',
    NICKNAME_EMPTY: '暱稱不能為空',
    NICKNAME_TOO_LONG: '暱稱長度不能超過50個字元',

    // 重設令牌驗證
    RESET_TOKEN_REQUIRED: '重設令牌為必填欄位',
    RESET_TOKEN_EMPTY: '重設令牌不能為空',

    // Refresh Token 驗證
    REFRESH_TOKEN_REQUIRED: 'refresh_token 為必填欄位',
    REFRESH_TOKEN_EMPTY: 'refresh_token 不能為空',
    REFRESH_TOKEN_INVALID_TYPE: 'refresh_token 必須為字串格式',

    // 管理員驗證
    ADMIN_USERNAME_REQUIRED: '管理員帳號為必填欄位',
    ADMIN_USERNAME_EMPTY: '管理員帳號不能為空',
    ADMIN_USERNAME_EXISTS: '管理員帳號已存在',
    ADMIN_EMAIL_EXISTS: '管理員電子郵件已存在',
    ADMIN_NAME_REQUIRED: '管理員姓名為必填欄位',
    ADMIN_NAME_EMPTY: '管理員姓名不能為空',
    ADMIN_PASSWORD_REQUIRED: '管理員密碼為必填欄位',
    ADMIN_PASSWORD_EMPTY: '管理員密碼不能為空',
    REJECTION_REASON_REQUIRED: '拒絕原因為必填欄位',
    REJECTION_REASON_EMPTY: '拒絕原因不能為空',

    // 工作經驗驗證
    WORKPLACE_REQUIRED: '工作地點為必填欄位',
    END_DATE_BEFORE_START_DATE: '結束日期不得早於開始日期',
    WORKING_END_DATE_NOT_ALLOWED: '在職工作經驗不可填寫結束日期',
    NON_WORKING_END_DATE_REQUIRED: '離職工作經驗必須填寫結束日期',

    // 學習經歷驗證
    INSTITUTION_REQUIRED: '教育機構為必填欄位',
    INSTITUTION_EMPTY: '教育機構不能為空',
    DEGREE_REQUIRED: '學位為必填欄位',
    DEGREE_EMPTY: '學位不能為空',
    FIELD_OF_STUDY_REQUIRED: '專業領域為必填欄位',
    FIELD_OF_STUDY_EMPTY: '專業領域不能為空',
    START_YEAR_REQUIRED: '開始年份為必填欄位',
    START_YEAR_INVALID: '開始年份格式不正確',
    END_YEAR_REQUIRED: '結束年份為必填欄位',
    END_YEAR_INVALID: '結束年份格式不正確',
    LEARNING_END_YEAR_BEFORE_START_YEAR: '結束年份不得早於開始年份',
    LEARNING_YEAR_RANGE_INVALID: '學習年份範圍不合理',
    LEARNING_GRADUATED_NO_END_DATE: '已畢業的學習經歷必須提供結束日期',

    // 課程驗證
    COURSE_NAME_REQUIRED: '課程名稱為必填欄位',
    COURSE_NAME_TOO_LONG: '課程名稱不能超過100個字元',
    COURSE_CONTENT_REQUIRED: '課程內容為必填欄位', 
    COURSE_CONTENT_TOO_LONG: '課程內容不能超過5000個字元',
    MAIN_CATEGORY_REQUIRED: '主分類為必填欄位',
    MAIN_CATEGORY_INVALID: '主分類格式不正確',
    SUB_CATEGORY_REQUIRED: '子分類為必填欄位',
    SUB_CATEGORY_INVALID: '子分類格式不正確',
    CITY_REQUIRED: '城市為必填欄位',
    CITY_INVALID: '城市格式不正確',
    SURVEY_URL_INVALID: '問卷連結格式不正確',
    PURCHASE_MESSAGE_TOO_LONG: '購買訊息不能超過500個字元',

    // 價格方案驗證
    PRICE_REQUIRED: '價格為必填欄位',
    PRICE_INVALID: '價格格式不正確',
    PRICE_TOO_LOW: '價格必須大於0',
    PRICE_TOO_HIGH: '價格不能超過999999',
    QUANTITY_REQUIRED: '堂數為必填欄位',
    QUANTITY_INVALID: '堂數格式不正確',
    QUANTITY_TOO_LOW: '堂數必須大於0',
    QUANTITY_TOO_HIGH: '堂數不能超過999',

    // 影片驗證
    VIDEO_NAME_REQUIRED: '影片名稱為必填欄位',
    VIDEO_NAME_EMPTY: '影片名稱不能為空',
    VIDEO_NAME_TOO_LONG: '影片名稱不能超過200個字元',
    VIDEO_CATEGORY_REQUIRED: '影片分類為必填欄位',
    VIDEO_CATEGORY_EMPTY: '影片分類不能為空',
    VIDEO_CATEGORY_TOO_LONG: '影片分類不能超過100個字元',
    VIDEO_INTRO_REQUIRED: '影片介紹為必填欄位',
    VIDEO_INTRO_EMPTY: '影片介紹不能為空',
    VIDEO_INTRO_TOO_LONG: '影片介紹不能超過2000個字元',
    VIDEO_TYPE_REQUIRED: '影片類型為必填欄位',
    VIDEO_TYPE_INVALID: '影片類型必須為 storage 或 youtube',
    VIDEO_FILE_REQUIRED: '本地儲存影片需要上傳檔案',
    VIDEO_FILE_TOO_LARGE: '影片檔案大小不能超過500MB',
    VIDEO_FILE_FORMAT_INVALID: '影片格式不支援，請上傳 MP4、AVI、MOV、WMV 格式',
    YOUTUBE_URL_REQUIRED: 'YouTube 影片需要提供網址',
    YOUTUBE_URL_INVALID: 'YouTube 網址格式不正確',
    YOUTUBE_URL_NOT_ALLOWED_FOR_STORAGE: '本地儲存影片不需要 YouTube 網址',
    THUMBNAIL_FILE_TOO_LARGE: '縮圖檔案大小不能超過5MB',
    THUMBNAIL_FILE_FORMAT_INVALID: '縮圖格式不支援，請上傳 JPG、JPEG、PNG 格式',
    
    // 課程檔案驗證
    COURSE_FILES_REQUIRED: '課程檔案為必填欄位',
    COURSE_FILES_EMPTY: '請至少上傳一個課程檔案',
    COURSE_FILE_TOO_LARGE: '檔案大小不能超過10MB',
    COURSE_FILE_FORMAT_INVALID: '檔案格式不支援，請上傳 PDF、DOC、DOCX、XLS、XLSX、PPT、PPTX、ZIP、RAR、JPG、JPEG、PNG 格式',
    COURSE_FILE_COUNT_EXCEEDED: '課程檔案數量不能超過50個',
    COURSE_FILE_UPLOAD_LIMIT_EXCEEDED: '單次上傳檔案數量不能超過5個',
    COURSE_FILE_NAME_REQUIRED: '檔案名稱為必填欄位',
    COURSE_FILE_NAME_TOO_LONG: '檔案名稱不能超過255個字元',
    
    // 頭像上傳驗證
    AVATAR_FILE_REQUIRED: '請選擇要上傳的頭像檔案',
    AVATAR_FILE_TOO_LARGE: '頭像檔案大小不能超過5MB',
    AVATAR_FILE_FORMAT_INVALID: '頭像格式不支援，請上傳 JPEG、JPG、PNG、WebP 格式',
    AVATAR_FILE_DIMENSIONS_INVALID: '頭像尺寸不能超過2000x2000像素',
    AVATAR_FILE_TOO_SMALL: '頭像尺寸不能小於100x100像素',
    AVATAR_FILE_CORRUPTED: '頭像檔案已損壞，請重新上傳',
    
    // 更新相關驗證
    UPDATE_DATA_REQUIRED: '至少需要提供一個欄位進行更新',
    
    // 分頁相關驗證
    PAGE_MUST_BE_NUMBER: '頁碼必須為數字',
    PAGE_MUST_BE_INTEGER: '頁碼必須為整數',
    PAGE_MUST_BE_POSITIVE: '頁碼必須大於0',
    PER_PAGE_MUST_BE_NUMBER: '每頁數量必須為數字',
    PER_PAGE_MUST_BE_INTEGER: '每頁數量必須為整數',
    PER_PAGE_MUST_BE_POSITIVE: '每頁數量必須大於0',
    PER_PAGE_TOO_LARGE: '每頁數量不能超過100',
    
    // 搜尋相關驗證
    SEARCH_QUERY_TOO_LONG: '搜尋關鍵字不能超過200個字元',
    SEARCH_METHODS_EXCLUSIVE: '關鍵字搜尋和分類搜尋不能同時使用',
    CATEGORY_SEARCH_INCOMPLETE: '使用分類搜尋時主分類和次分類都必填',
    SORT_OPTION_INVALID: '排序方式只能是 newest, popular, price_low, price_high',
    
    // 評價相關驗證
    REVIEW_RATING_INVALID: '評分篩選必須為1-5的整數',
    REVIEW_SORT_INVALID: '排序方式只能是 newest, oldest, rating_high, rating_low',
    REVIEW_RESERVATION_ID_REQUIRED: '預約ID為必填欄位',
    REVIEW_RESERVATION_ID_INVALID: '預約ID格式不正確',
    REVIEW_RATE_REQUIRED: '評分為必填欄位',
    REVIEW_RATE_INVALID: '評分格式不正確',
    REVIEW_RATE_OUT_OF_RANGE: '評分必須在1-5分之間',
    REVIEW_COMMENT_REQUIRED: '評價內容為必填欄位',
    REVIEW_COMMENT_EMPTY: '評價內容不能為空',
    REVIEW_COMMENT_TOO_SHORT: '評價內容至少需要50個字元',
    REVIEW_COMMENT_TOO_LONG: '評價內容不能超過500個字元',
    REVIEW_FILTER_RATING_INVALID: '篩選評分必須在1-5之間',
    REVIEW_FILTER_DATE_FORMAT_INVALID: '日期格式必須為 YYYY-MM-DD',
    REVIEW_FILTER_KEYWORD_TOO_LONG: '搜尋關鍵字不能超過100個字元',
    
    // 收藏相關驗證
    COURSE_ID_REQUIRED: '課程ID為必填欄位',
    COURSE_ID_INVALID: '課程ID格式不正確',
    
    // ID 參數驗證
    VIDEO_ID_REQUIRED: '影片ID為必填欄位',
    VIDEO_ID_MUST_BE_NUMBER: '影片ID必須為數字',
    VIDEO_ID_MUST_BE_INTEGER: '影片ID必須為整數',
    VIDEO_ID_MUST_BE_POSITIVE: '影片ID必須大於0',

    // 課程影片關聯驗證
    VIDEO_IDS_REQUIRED: '影片ID陣列為必填欄位',
    VIDEO_IDS_EMPTY: '影片ID陣列不能為空',
    VIDEO_IDS_INVALID: '影片ID陣列格式不正確',
    VIDEO_ID_INVALID: '影片ID格式不正確',
    VIDEO_ORDERS_REQUIRED: '影片順序陣列為必填欄位',
    VIDEO_ORDERS_EMPTY: '影片順序陣列不能為空',
    VIDEO_ORDERS_INVALID: '影片順序陣列格式不正確',
    DISPLAY_ORDER_REQUIRED: '顯示順序為必填欄位',
    DISPLAY_ORDER_INVALID: '顯示順序必須為正整數',
    IS_PREVIEW_INVALID: '預覽設定必須為布林值',

    // 時段驗證
    INVALID_SLOT_IDS: '時段ID格式不正確，必須為數字格式',

    // 一般驗證
    FIELD_REQUIRED: (field: string) => `${field}為必填欄位`,
    FIELD_INVALID_TYPE: (field: string, type: string) => `${field}必須為${type}格式`,

    // 付款相關驗證
    PAYMENT_ORDER_ID_INVALID: '訂單ID格式不正確',

    // 預約相關驗證
    RESERVATION_COURSE_ID_REQUIRED: '課程ID為必填欄位',
    RESERVATION_COURSE_ID_INVALID: '課程ID格式不正確',
    RESERVATION_TEACHER_ID_REQUIRED: '教師ID為必填欄位',
    RESERVATION_TEACHER_ID_INVALID: '教師ID格式不正確',
    RESERVATION_DATE_REQUIRED: '預約日期為必填欄位',
    RESERVATION_DATE_INVALID: '預約日期格式不正確，請使用 YYYY-MM-DD 格式',
    RESERVATION_TIME_REQUIRED: '預約時間為必填欄位',
    RESERVATION_TIME_INVALID: '預約時間格式不正確，請使用 HH:mm 格式',
    RESERVATION_STATUS_TYPE_REQUIRED: '狀態類型為必填欄位',
    RESERVATION_STATUS_TYPE_INVALID: '狀態類型必須為 teacher-complete 或 student-complete',
    RESERVATION_CALENDAR_VIEW_REQUIRED: '日曆檢視模式為必填欄位',
    RESERVATION_CALENDAR_VIEW_INVALID: '日曆檢視模式必須為 week 或 month',
    RESERVATION_CALENDAR_DATE_REQUIRED: '基準日期為必填欄位',
    RESERVATION_CALENDAR_DATE_INVALID: '基準日期格式不正確，請使用 YYYY-MM-DD 格式',
    RESERVATION_INVALID_TIME_FORMAT: '時間格式不正確',
    RESERVATION_INVALID_DATE_FORMAT: '日期格式不正確',

    // === 評價相關驗證 ===
    REVIEW: {
      RESERVATION_UUID_REQUIRED: '預約UUID為必填欄位',
      RESERVATION_UUID_INVALID: '預約UUID格式不正確',
      RATING_REQUIRED: '評分為必填欄位',
      RATING_INVALID: '評分必須為1-5的整數',
      CONTENT_REQUIRED: '評價內容為必填欄位',
      RATING_FILTER_INVALID: '評分篩選必須為1-5的整數',
    },

    // === 通用驗證訊息 ===
    COMMON: {
      PAGE_INVALID: '頁碼必須為大於0的整數',
      LIMIT_INVALID: '每頁數量必須為1-100的整數',
      SORT_BY_INVALID: '排序欄位格式不正確',
      SORT_ORDER_INVALID: '排序方向必須為 asc 或 desc',
      COURSE_ID_INVALID: '課程ID必須為大於0的整數',
      COURSE_UUID_REQUIRED: '課程UUID為必填欄位',
      COURSE_UUID_INVALID: '課程UUID格式不正確',
    },
  },

  // === 業務邏輯訊息 ===
  BUSINESS: {
    // 為了向後相容性，保留原本在 BUSINESS 中的認證錯誤訊息
    REGISTRATION_FAILED: '註冊失敗',
    LOGIN_FAILED: '登入失敗',

    // 資源不存在
    USER_NOT_FOUND: '使用者不存在',
    ADMIN_USER_NOT_FOUND: '管理員帳號不存在',
    TEACHER_NOT_FOUND: '找不到教師記錄',
    STUDENT_NOT_FOUND: '找不到學生記錄',
    COURSE_NOT_FOUND: '課程不存在',
    APPLICATION_NOT_FOUND: '找不到申請記錄',
    TEACHER_APPLICATION_NOT_FOUND: '找不到教師申請記錄',
    COURSE_APPLICATION_NOT_FOUND: '找不到課程申請記錄',
    WORK_EXPERIENCE_NOT_FOUND: '找不到工作經驗記錄',
    WORK_EXPERIENCE_RECORD_NOT_FOUND: '工作經驗記錄不存在',
    LEARNING_EXPERIENCE_NOT_FOUND: '找不到學習經歷記錄',
    LEARNING_EXPERIENCE_RECORD_NOT_FOUND: '學習經歷記錄不存在',
    PRICE_OPTION_NOT_FOUND: '找不到價格方案',
    VIDEO_NOT_FOUND: '找不到影片',
    COURSE_VIDEO_NOT_FOUND: '找不到課程影片關聯',
    COURSE_FILE_NOT_FOUND: '找不到課程檔案',
    SETTLEMENT_NOT_FOUND: '找不到結算記錄',
    EARNING_RECORD_NOT_FOUND: '找不到收入記錄',

    // 權限與授權
    UNAUTHORIZED_ACCESS: '您沒有權限執行此操作',
    UNAUTHORIZED_WORK_EXPERIENCE_ACCESS: '無權存取此工作經驗記錄',
    UNAUTHORIZED_WORK_EXPERIENCE_DELETE: '無權刪除此工作經驗記錄',
    UNAUTHORIZED_LEARNING_EXPERIENCE_ACCESS: '無權存取此學習經歷記錄',
    UNAUTHORIZED_LEARNING_EXPERIENCE_DELETE: '無權刪除此學習經歷記錄',
    TEACHER_PERMISSION_REQUIRED: '需要教師權限才能執行此操作',

    // 業務規則
    APPLICATION_EXISTS: '您已提交過教師申請',
    APPLICATION_ALREADY_REVIEWED: '申請已被審核，無法重複操作',
    APPLICATION_STATUS_NOT_PENDING: '只能審核待審核狀態的申請',
    STUDENT_ONLY_APPLY_TEACHER: '只有學生可以申請成為教師',
    ACCOUNT_STATUS_INVALID: '帳號狀態異常',
    APPLICATION_STATUS_INVALID: '只能在待審核或已拒絕狀態下修改申請',
    COURSE_PUBLISHED_CANNOT_DELETE: '已發布的課程不能直接刪除',
    TEACHER_NOT_APPROVED: '教師申請尚未核准',
    COURSE_NOT_DRAFT: '只能操作草稿狀態的課程',
    COURSE_NOT_APPROVED: '課程尚未通過審核',
    COURSE_ALREADY_PUBLISHED: '課程已經發布',
    COURSE_CANNOT_SUBMIT: '課程無法提交審核',
    COURSE_CANNOT_RESUBMIT: '只有被拒絕的課程才能重新提交',
    COURSE_CANNOT_PUBLISH: '課程無法發布',
    COURSE_CANNOT_ARCHIVE: '課程無法封存',
    COURSE_UNDER_REVIEW: '課程正在審核中，無法修改',
    
    // 價格方案業務規則
    PRICE_OPTION_DUPLICATE: '此價格和堂數組合已存在',
    PRICE_OPTION_LIMIT_EXCEEDED: '每個課程最多只能有3個價格方案',
    PRICE_OPTION_LAST_ONE: '不能刪除最後一個價格方案',
    PRICE_OPTION_HAS_PURCHASES: '此價格方案已有購買記錄，無法刪除',
    
    // 影片業務規則
    VIDEO_PERMISSION_REQUIRED: '只能管理自己的影片',
    VIDEO_IN_USE: '此影片正被課程使用，無法刪除',
    VIDEO_CANNOT_DELETE: '無法刪除影片',
    VIDEO_UPLOAD_FAILED: '影片上傳失敗',
    VIDEO_PROCESSING_FAILED: '影片處理失敗',
    
    // 課程影片關聯業務規則
    COURSE_VIDEO_ALREADY_LINKED: '課程已關聯此影片',
    COURSE_VIDEO_NOT_LINKED: '課程尚未關聯此影片',
    VIDEO_NOT_OWNED_BY_TEACHER: '無法關聯其他教師的影片',
    COURSE_VIDEO_DUPLICATE_ORDER: '影片順序重複',
    COURSE_VIDEO_MISSING_VIDEOS: '指定的影片不存在於課程中',
    COURSE_VIDEO_INVALID_ORDER: '影片順序設定無效',
    
    // 課程檔案業務規則
    COURSE_FILE_PERMISSION_REQUIRED: '只能管理自己課程的檔案',
    COURSE_FILE_UPLOAD_FAILED: '檔案上傳失敗',
    COURSE_FILE_DELETE_FAILED: '檔案刪除失敗',
    COURSE_FILE_LIMIT_REACHED: '課程檔案數量已達上限',
    
    // 頭像上傳業務規則
    AVATAR_UPLOAD_FAILED: '頭像上傳失敗，請重試',
    AVATAR_DELETE_FAILED: '舊頭像刪除失敗',
    AVATAR_PROCESSING_FAILED: '頭像處理失敗，請重新上傳',
    AVATAR_UPDATE_FAILED: '頭像更新失敗，請重試',
    
    // 課程瀏覽相關
    COURSE_NOT_PUBLISHED: '課程未發布或不存在',
    COURSE_TEACHER_INACTIVE: '課程教師帳號已停用',
    
    // 收藏功能相關
    FAVORITE_ALREADY_EXISTS: '課程已在收藏清單中',
    FAVORITE_NOT_FOUND: '收藏記錄不存在',
    CANNOT_FAVORITE_OWN_COURSE: '不能收藏自己的課程',

    // 購物車相關
    CART_ITEM_NOT_FOUND: '購物車項目不存在',
    CART_EMPTY: '購物車為空',
    CANNOT_PURCHASE_OWN_COURSE: '不能購買自己的課程',
    UNAUTHORIZED_CART_ACCESS: '無權存取此購物車項目',

    // 訂單相關
    ORDER_NOT_FOUND: '訂單不存在',
    UNAUTHORIZED_ORDER_ACCESS: '無權存取此訂單',
    ORDER_ALREADY_CANCELLED: '訂單已取消',
    ORDER_STATUS_INVALID_FOR_CANCEL: '此狀態的訂單無法取消',
    ORDER_ALREADY_PAID: '訂單已付款',
    ORDER_STATUS_INVALID_FOR_PAYMENT: '此狀態的訂單無法付款',

    // 購買記錄相關
    PURCHASE_NOT_FOUND: '購買記錄不存在',
    INSUFFICIENT_PURCHASE_QUANTITY: '購買堂數不足',

    // 預約相關
    RESERVATION_NOT_FOUND: '預約記錄不存在',
    RESERVATION_CONFLICT: '預約時段衝突',
    RESERVATION_TIME_SLOT_OCCUPIED: '該時段已被其他學生預約',
    RESERVATION_TEACHER_UNAVAILABLE: '該時段教師不可預約',
    RESERVATION_COURSE_NOT_PURCHASED: '您尚未購買此課程',
    RESERVATION_INSUFFICIENT_LESSONS: '課程堂數不足',
    RESERVATION_ADVANCE_BOOKING_REQUIRED: '預約時間必須至少提前24小時',
    RESERVATION_CANCEL_TIME_LIMIT: '課程開始前24小時內無法取消',
    RESERVATION_ALREADY_CANCELLED: '預約已被取消',
    RESERVATION_ALREADY_COMPLETED: '預約已完成',
    RESERVATION_STATUS_INVALID: '預約狀態無效',
    RESERVATION_UNAUTHORIZED_ACCESS: '無權限操作此預約',
    RESERVATION_TEACHER_NOT_COMPLETED: '教師尚未標記課程完成',
    RESERVATION_STUDENT_NOT_COMPLETED: '學生尚未確認課程完成',
    RESERVATION_INVALID_STATUS_TRANSITION: '無效的狀態轉換',
    RESERVATION_PAST_TIME_NOT_ALLOWED: '不能預約過去的時間',
    RESERVATION_WEEKEND_SLOT_INVALID: '週末時段設定無效',

    // 評價業務規則錯誤
    REVIEW_NOT_FOUND: '評價記錄不存在',
    REVIEW_ALREADY_EXISTS: '此預約已有評價記錄',
    REVIEW_RESERVATION_NOT_COMPLETED: '課程尚未結束或已取消，無法評價',
    REVIEW_RESERVATION_NOT_OWNED: '無權評價此預約',
    REVIEW_COURSE_NOT_PURCHASED: '未購買此課程，無法評價',
    REVIEW_UNAUTHORIZED_ACCESS: '無權存取此評價',
    REVIEW_NOT_OWNED: '無權修改此評價',
    REVIEW_SUBMISSION_FAILED: '評價提交失敗',
    REVIEW_UPDATE_FAILED: '評價更新失敗',
    REVIEW_DELETE_FAILED: '評價刪除失敗',

    // 教師後台管理相關業務規則
    TEACHER_DASHBOARD_ACCESS_DENIED: '您沒有權限查看此教師後台資料',
    STUDENT_NOT_TEACHER_STUDENT: '該學生不是您的學生',
    STATISTICS_QUERY_FAILED: '統計數據查詢失敗',
    DATE_RANGE_INVALID: '日期範圍無效',
    DASHBOARD_DATA_UNAVAILABLE: '儀表板資料暫時無法取得',
  },

  // === 管理員訊息 ===
  ADMIN: {
    // 成功訊息
    TEACHER_APPLICATION_APPROVED: '教師申請已核准',
    TEACHER_APPLICATION_REJECTED: '教師申請已拒絕',
    COURSE_APPLICATION_APPROVED: '課程申請已核准',
    COURSE_APPLICATION_REJECTED: '課程申請已拒絕',
    TEACHER_APPLICATIONS_RETRIEVED: '成功獲取教師申請列表',
    COURSE_APPLICATIONS_RETRIEVED: '成功獲取課程申請列表',

    // 錯誤訊息
    APPROVAL_FAILED: '核准操作失敗',
    REJECTION_FAILED: '拒絕操作失敗',
  },

  // === 系統訊息 ===
  SYSTEM: {
    INTERNAL_ERROR: '系統內部錯誤',
    DATABASE_ERROR: '資料庫連接錯誤',
    VALIDATION_FAILED: '參數驗證失敗',
    VALIDATION_ERROR: '參數驗證失敗',
    TEACHER_APPLICATION_VALIDATION_FAILED: '教師申請參數驗證失敗',
    UNKNOWN_ERROR: '未知錯誤',
  },

  // === 工作經驗相關訊息 ===
  WORK_EXPERIENCE: {
    // 成功訊息
    LIST_SUCCESS: '取得工作經驗列表成功',
    CREATED: '工作經驗已新增',
    UPDATED: '工作經驗已更新',
    DELETED: '工作經驗已刪除',
  },

  // === 學習經歷相關訊息 ===
  LEARNING_EXPERIENCE: {
    // 成功訊息
    LIST_SUCCESS: '取得學習經歷列表成功',
    CREATED: '學習經歷已新增',
    UPDATED: '學習經歷已更新',
    DELETED: '學習經歷已刪除',
  },

  // === 課程相關訊息 ===
  COURSE: {
    // 成功訊息
    CREATED: '課程建立成功',
    UPDATED: '課程更新成功',
    DELETED: '課程已刪除',
    SUBMITTED: '課程已提交審核',
    RESUBMITTED: '課程已重新提交審核',
    PUBLISHED: '課程已成功發布',
    ARCHIVED: '課程已封存',
  },

  // === 價格方案相關訊息 ===
  PRICE_OPTION: {
    // 成功訊息
    LIST_SUCCESS: '取得價格方案列表成功',
    CREATED: '價格方案新增成功',
    UPDATED: '價格方案更新成功',
    DELETED: '價格方案已刪除',
  },

  // === 影片相關訊息 ===
  VIDEO: {
    // 成功訊息
    UPLOADED: '影片上傳成功',
    UPDATED: '影片資訊更新成功',
    DELETED: '影片已刪除',
    LIST_SUCCESS: '取得影片列表成功',
    DETAIL_SUCCESS: '取得影片詳情成功',
  },

  // === 課程影片關聯相關訊息 ===
  COURSE_VIDEO: {
    // 成功訊息
    LINKED: '影片關聯成功',
    ORDER_UPDATED: '影片順序更新成功',
    REMOVED: '影片已從課程中移除',
    LIST_SUCCESS: '取得課程影片列表成功',
  },

  // === 課程檔案相關訊息 ===
  COURSE_FILE: {
    // 成功訊息
    LIST_SUCCESS: '取得課程檔案列表成功',
    UPLOADED: '檔案上傳成功',
    DELETED: '檔案已刪除',
    EXISTS_CHECK_SUCCESS: '檔案存在性檢查完成',
  },

  // === 證書相關訊息 ===
  CERTIFICATE: {
    // 成功訊息
    LIST_SUCCESS: '取得證書列表成功',
    CREATED: '證書已新增',
    UPDATED: '證書已更新',
    DELETED: '證書已刪除',
  },

  // === 評價系統相關訊息 ===
  REVIEW: {
    // 成功訊息
    SUBMIT_SUCCESS: '評價提交成功',
    LIST_SUCCESS: '取得評價列表成功',
    MY_REVIEWS_SUCCESS: '取得我的評價列表成功',
    RECEIVED_REVIEWS_SUCCESS: '取得收到的評價成功',
    FILTER_SUCCESS: '評價篩選成功',
    STATS_SUCCESS: '取得評價統計成功',
    COURSE_REVIEWS_SUCCESS: '取得課程評價成功',
    UPDATE_SUCCESS: '評價更新成功',
    DELETE_SUCCESS: '評價刪除成功',
  },

  // === 公開課程相關訊息 ===
  PUBLIC_COURSE: {
    // 成功訊息
    LIST_SUCCESS: '取得課程列表成功',
    DETAIL_SUCCESS: '取得課程詳情成功',
    REVIEWS_SUCCESS: '取得課程評價成功',
    NO_COURSES_FOUND: '沒有找到符合條件的課程',
  },

  // === 收藏功能相關訊息 ===
  FAVORITE: {
    // 成功訊息
    ADDED: '課程已加入收藏',
    REMOVED: '已移除課程收藏',
    LIST_SUCCESS: '取得收藏清單成功',
    STATUS_CHECK_SUCCESS: '收藏狀態查詢成功',
  },

  // === 教師申請相關訊息 ===
  TEACHER: {
    // 成功訊息
    APPLICATION_CREATED: '教師申請已建立',
    APPLICATION_GET_SUCCESS: '取得申請狀態成功',
    APPLICATION_UPDATED: '申請資料更新成功',
    APPLICATION_RESUBMITTED: '申請已重新提交',
    PROFILE_GET_SUCCESS: '取得教師資料成功',
    PROFILE_UPDATED: '教師資料更新成功',
    PROFILE_UPDATE_NOTICE: '由於修改了重要資料，需要重新審核',
    WORK_EXPERIENCE_LIST_SUCCESS: '取得工作經驗列表成功',
    WORK_EXPERIENCE_CREATED: '工作經驗已新增',
    WORK_EXPERIENCE_UPDATED: '工作經驗已更新',
    APPLICATION_SUBMITTED: '教師申請已提交，等待審核',
  },

  // === 教師公開資料相關訊息 ===
  PUBLIC_TEACHER: {
    // 成功訊息
    PROFILE_SUCCESS: '取得教師資料成功',
    COURSES_SUCCESS: '取得教師課程列表成功',
  },

  // === 時段管理相關訊息 ===
  SCHEDULE: {
    // 成功訊息
    SETTINGS_GET_SUCCESS: '取得教師時段設定成功',
    SETTINGS_UPDATE_SUCCESS: '教師時段設定更新成功',
    CONFLICT_CHECK_SUCCESS: '時段衝突檢查完成',
  },

  // === 購物車相關訊息 ===
  CART: {
    // 成功訊息
    ITEM_ADDED: '課程已加入購物車',
    ITEM_UPDATED: '購物車項目已更新',
    ITEM_REMOVED: '商品已從購物車移除',
    CLEARED: '購物車已清空',
    LIST_SUCCESS: '取得購物車內容成功',
  },

  // === 訂單相關訊息 ===
  ORDER: {
    // 成功訊息
    CREATED: '訂單建立成功',
    LIST_SUCCESS: '取得訂單列表成功',
    DETAIL_SUCCESS: '取得訂單詳情成功',
    CANCELLED: '訂單已取消',
  },

  // === 付款相關訊息 ===
  PAYMENT: {
    // 成功訊息
    PROCESSING_SUCCESS: '付款處理成功',
    COMPLETED: '付款已完成',
  },

  // === 購買記錄相關訊息 ===
  PURCHASE: {
    // 成功訊息
    LIST_SUCCESS: '取得購買記錄成功',
    DETAIL_SUCCESS: '取得課程購買記錄成功',
  },

  // === 預約管理相關訊息 ===
  RESERVATION: {
    // 成功訊息
    CREATED: '預約建立成功',
    LIST_SUCCESS: '取得預約列表成功',
    DETAIL_SUCCESS: '取得預約詳情成功',
    STATUS_UPDATED: '預約狀態更新成功',
    TEACHER_COMPLETED: '教師已標記課程完成',
    STUDENT_COMPLETED: '學生已確認課程完成',
    FULLY_COMPLETED: '課程已完全完成',
    CANCELLED: '預約已取消',
    LESSONS_REFUNDED: '堂數已退回',
    CALENDAR_SUCCESS: '取得日曆資料成功',
    CONFLICT_CHECK_SUCCESS: '預約衝突檢查完成',
    VALIDATION_SUCCESS: '預約條件驗證完成',
  },

  // === 教師後台管理相關訊息 ===
  TEACHER_DASHBOARD: {
    // 成功訊息
    DASHBOARD_SUCCESS: '取得儀表板數據成功',
    STATS_SUCCESS: '取得教師統計數據成功',
    PERFORMANCE_SUCCESS: '取得教師表現數據成功',
    STUDENTS_LIST_SUCCESS: '取得學生列表成功',
    STUDENT_DETAIL_SUCCESS: '取得學生詳情成功',
    STUDENT_PURCHASES_SUCCESS: '取得學生購買記錄成功',
    STUDENT_RESERVATIONS_SUCCESS: '取得學生預約記錄成功',
    RESERVATION_LIST_SUCCESS: '取得預約列表成功',
    UPDATE_RESERVATION_SUCCESS: '更新預約狀態成功',
    SETTLEMENT_DETAIL_SUCCESS: '取得結算詳情成功',
    EARNINGS_SUCCESS: '取得收入明細成功',
    SETTLEMENTS_SUCCESS: '取得結算記錄成功',
    EARNINGS_STATS_SUCCESS: '取得收入統計成功',
  },
} as const

// === 便捷訪問器 ===
export const AuthMessages = MESSAGES.AUTH
export const ValidationMessages = MESSAGES.VALIDATION
export const BusinessMessages = MESSAGES.BUSINESS
export const SystemMessages = MESSAGES.SYSTEM
export const WorkExperienceMessages = MESSAGES.WORK_EXPERIENCE
export const LearningExperienceMessages = MESSAGES.LEARNING_EXPERIENCE
export const CourseMessages = MESSAGES.COURSE
export const PriceOptionMessages = MESSAGES.PRICE_OPTION
export const VideoMessages = MESSAGES.VIDEO
export const CourseVideoMessages = MESSAGES.COURSE_VIDEO
export const CourseFileMessages = MESSAGES.COURSE_FILE
export const PublicCourseMessages = MESSAGES.PUBLIC_COURSE
export const FavoriteMessages = MESSAGES.FAVORITE
export const PublicTeacherMessages = MESSAGES.PUBLIC_TEACHER
export const ReservationMessages = MESSAGES.RESERVATION
export const TeacherDashboardMessages = MESSAGES.TEACHER_DASHBOARD

// === 向後相容性：SUCCESS 物件 ===
// 為了保持向後相容，維持原有的 SUCCESS 分組
export const SUCCESS = {
  REGISTRATION_SUCCESS: MESSAGES.AUTH.REGISTRATION_SUCCESS,
  LOGIN_SUCCESS: MESSAGES.AUTH.LOGIN_SUCCESS,
  PROFILE_RETRIEVED: MESSAGES.AUTH.PROFILE_RETRIEVED,
  PROFILE_UPDATED: MESSAGES.AUTH.PROFILE_UPDATED,
  ACCOUNT_DELETED: MESSAGES.AUTH.ACCOUNT_DELETED,
  PASSWORD_RESET_EMAIL_SENT: MESSAGES.AUTH.PASSWORD_RESET_EMAIL_SENT,
  PASSWORD_RESET_SUCCESS: MESSAGES.AUTH.PASSWORD_RESET_SUCCESS,
  TOKEN_REFRESH_SUCCESS: MESSAGES.AUTH.TOKEN_REFRESH_SUCCESS,
  
  // 工作經驗相關成功訊息
  WORK_EXPERIENCE_LIST_SUCCESS: MESSAGES.WORK_EXPERIENCE.LIST_SUCCESS,
  WORK_EXPERIENCE_CREATED: MESSAGES.WORK_EXPERIENCE.CREATED,
  WORK_EXPERIENCE_UPDATED: MESSAGES.WORK_EXPERIENCE.UPDATED,
  WORK_EXPERIENCE_DELETED: MESSAGES.WORK_EXPERIENCE.DELETED,
  
  // 學習經歷相關成功訊息
  LEARNING_EXPERIENCE_LIST_SUCCESS: MESSAGES.LEARNING_EXPERIENCE.LIST_SUCCESS,
  LEARNING_EXPERIENCE_CREATED: MESSAGES.LEARNING_EXPERIENCE.CREATED,
  LEARNING_EXPERIENCE_UPDATED: MESSAGES.LEARNING_EXPERIENCE.UPDATED,
  LEARNING_EXPERIENCE_DELETED: MESSAGES.LEARNING_EXPERIENCE.DELETED,
  
  // 課程相關成功訊息
  COURSE_CREATED: MESSAGES.COURSE.CREATED,
  COURSE_UPDATED: MESSAGES.COURSE.UPDATED,
  COURSE_DELETED: MESSAGES.COURSE.DELETED,
  COURSE_SUBMITTED: MESSAGES.COURSE.SUBMITTED,
  COURSE_RESUBMITTED: MESSAGES.COURSE.RESUBMITTED,
  COURSE_PUBLISHED: MESSAGES.COURSE.PUBLISHED,
  COURSE_ARCHIVED: MESSAGES.COURSE.ARCHIVED,
  
  // 價格方案相關成功訊息
  PRICE_OPTION_LIST_SUCCESS: MESSAGES.PRICE_OPTION.LIST_SUCCESS,
  PRICE_OPTION_CREATED: MESSAGES.PRICE_OPTION.CREATED,
  PRICE_OPTION_UPDATED: MESSAGES.PRICE_OPTION.UPDATED,
  PRICE_OPTION_DELETED: MESSAGES.PRICE_OPTION.DELETED,
  
  // 影片相關成功訊息
  VIDEO_UPLOADED: MESSAGES.VIDEO.UPLOADED,
  VIDEO_UPDATED: MESSAGES.VIDEO.UPDATED,
  VIDEO_DELETED: MESSAGES.VIDEO.DELETED,
  VIDEO_LIST_SUCCESS: MESSAGES.VIDEO.LIST_SUCCESS,
  VIDEO_DETAIL_SUCCESS: MESSAGES.VIDEO.DETAIL_SUCCESS,
  
  // 課程影片關聯相關成功訊息
  COURSE_VIDEO_LINKED: MESSAGES.COURSE_VIDEO.LINKED,
  COURSE_VIDEO_ORDER_UPDATED: MESSAGES.COURSE_VIDEO.ORDER_UPDATED,
  COURSE_VIDEO_REMOVED: MESSAGES.COURSE_VIDEO.REMOVED,
  COURSE_VIDEO_LIST_SUCCESS: MESSAGES.COURSE_VIDEO.LIST_SUCCESS,
  
  // 課程檔案相關成功訊息
  COURSE_FILE_LIST_SUCCESS: MESSAGES.COURSE_FILE.LIST_SUCCESS,
  COURSE_FILE_UPLOADED: MESSAGES.COURSE_FILE.UPLOADED,
  COURSE_FILE_DELETED: MESSAGES.COURSE_FILE.DELETED,
  
  // 公開課程相關成功訊息
  PUBLIC_COURSE_LIST_SUCCESS: MESSAGES.PUBLIC_COURSE.LIST_SUCCESS,
  PUBLIC_COURSE_DETAIL_SUCCESS: MESSAGES.PUBLIC_COURSE.DETAIL_SUCCESS,
  PUBLIC_COURSE_REVIEWS_SUCCESS: MESSAGES.PUBLIC_COURSE.REVIEWS_SUCCESS,
  PUBLIC_COURSE_NO_COURSES_FOUND: MESSAGES.PUBLIC_COURSE.NO_COURSES_FOUND,
  
  // 收藏功能相關成功訊息
  FAVORITE_ADDED: MESSAGES.FAVORITE.ADDED,
  FAVORITE_REMOVED: MESSAGES.FAVORITE.REMOVED,
  FAVORITE_LIST_SUCCESS: MESSAGES.FAVORITE.LIST_SUCCESS,
  FAVORITE_STATUS_CHECK_SUCCESS: MESSAGES.FAVORITE.STATUS_CHECK_SUCCESS,
  
  // 教師公開資料相關成功訊息
  PUBLIC_TEACHER_PROFILE_SUCCESS: MESSAGES.PUBLIC_TEACHER.PROFILE_SUCCESS,
  PUBLIC_TEACHER_COURSES_SUCCESS: MESSAGES.PUBLIC_TEACHER.COURSES_SUCCESS,

  // 教師申請相關成功訊息
  TEACHER_APPLICATION_CREATED: MESSAGES.TEACHER.APPLICATION_CREATED,
  TEACHER_APPLICATION_GET_SUCCESS: MESSAGES.TEACHER.APPLICATION_GET_SUCCESS,
  TEACHER_APPLICATION_UPDATED: MESSAGES.TEACHER.APPLICATION_UPDATED,
  TEACHER_APPLICATION_RESUBMITTED: MESSAGES.TEACHER.APPLICATION_RESUBMITTED,
  TEACHER_PROFILE_GET_SUCCESS: MESSAGES.TEACHER.PROFILE_GET_SUCCESS,
  TEACHER_PROFILE_UPDATED: MESSAGES.TEACHER.PROFILE_UPDATED,
  TEACHER_WORK_EXPERIENCE_LIST_SUCCESS: MESSAGES.TEACHER.WORK_EXPERIENCE_LIST_SUCCESS,
  TEACHER_WORK_EXPERIENCE_CREATED: MESSAGES.TEACHER.WORK_EXPERIENCE_CREATED,
  TEACHER_WORK_EXPERIENCE_UPDATED: MESSAGES.TEACHER.WORK_EXPERIENCE_UPDATED,
  TEACHER_APPLICATION_SUBMITTED: MESSAGES.TEACHER.APPLICATION_SUBMITTED,

  // 購物車相關成功訊息
  CART_ITEM_ADDED: MESSAGES.CART.ITEM_ADDED,
  CART_ITEM_UPDATED: MESSAGES.CART.ITEM_UPDATED,
  CART_ITEM_REMOVED: MESSAGES.CART.ITEM_REMOVED,
  CART_CLEARED: MESSAGES.CART.CLEARED,
  CART_LIST_SUCCESS: MESSAGES.CART.LIST_SUCCESS,

  // 訂單相關成功訊息
  ORDER_CREATED: MESSAGES.ORDER.CREATED,
  ORDER_LIST_SUCCESS: MESSAGES.ORDER.LIST_SUCCESS,
  ORDER_DETAIL_SUCCESS: MESSAGES.ORDER.DETAIL_SUCCESS,
  ORDER_CANCELLED: MESSAGES.ORDER.CANCELLED,

  // 付款相關成功訊息
  PAYMENT_PROCESSING_SUCCESS: MESSAGES.PAYMENT.PROCESSING_SUCCESS,
  PAYMENT_COMPLETED: MESSAGES.PAYMENT.COMPLETED,

  // 購買記錄相關成功訊息
  PURCHASE_LIST_SUCCESS: MESSAGES.PURCHASE.LIST_SUCCESS,
  PURCHASE_DETAIL_SUCCESS: MESSAGES.PURCHASE.DETAIL_SUCCESS,

  // 預約管理相關成功訊息
  RESERVATION_CREATED: MESSAGES.RESERVATION.CREATED,
  RESERVATION_LIST_SUCCESS: MESSAGES.RESERVATION.LIST_SUCCESS,
  RESERVATION_DETAIL_SUCCESS: MESSAGES.RESERVATION.DETAIL_SUCCESS,
  RESERVATION_STATUS_UPDATED: MESSAGES.RESERVATION.STATUS_UPDATED,
  RESERVATION_TEACHER_COMPLETED: MESSAGES.RESERVATION.TEACHER_COMPLETED,
  RESERVATION_STUDENT_COMPLETED: MESSAGES.RESERVATION.STUDENT_COMPLETED,
  RESERVATION_FULLY_COMPLETED: MESSAGES.RESERVATION.FULLY_COMPLETED,
  RESERVATION_CANCELLED: MESSAGES.RESERVATION.CANCELLED,
  RESERVATION_LESSONS_REFUNDED: MESSAGES.RESERVATION.LESSONS_REFUNDED,
  RESERVATION_CALENDAR_SUCCESS: MESSAGES.RESERVATION.CALENDAR_SUCCESS,
  RESERVATION_CONFLICT_CHECK_SUCCESS: MESSAGES.RESERVATION.CONFLICT_CHECK_SUCCESS,

  // 評價系統相關成功訊息
  REVIEW_SUBMIT_SUCCESS: MESSAGES.REVIEW.SUBMIT_SUCCESS,
  REVIEW_LIST_SUCCESS: MESSAGES.REVIEW.LIST_SUCCESS,
  REVIEW_MY_REVIEWS_SUCCESS: MESSAGES.REVIEW.MY_REVIEWS_SUCCESS,
  REVIEW_RECEIVED_REVIEWS_SUCCESS: MESSAGES.REVIEW.RECEIVED_REVIEWS_SUCCESS,
  REVIEW_FILTER_SUCCESS: MESSAGES.REVIEW.FILTER_SUCCESS,
  REVIEW_STATS_SUCCESS: MESSAGES.REVIEW.STATS_SUCCESS,
  REVIEW_COURSE_REVIEWS_SUCCESS: MESSAGES.REVIEW.COURSE_REVIEWS_SUCCESS,
  REVIEW_UPDATE_SUCCESS: MESSAGES.REVIEW.UPDATE_SUCCESS,
  REVIEW_DELETE_SUCCESS: MESSAGES.REVIEW.DELETE_SUCCESS,

  // 時段設定相關成功訊息
  RESERVATION_VALIDATION_SUCCESS: MESSAGES.RESERVATION.VALIDATION_SUCCESS,

  // 證書相關成功訊息
  CERTIFICATE_DELETED: MESSAGES.CERTIFICATE.DELETED,

  // 課程檔案相關成功訊息
  COURSE_FILE_EXISTS_CHECK_SUCCESS: MESSAGES.COURSE_FILE.EXISTS_CHECK_SUCCESS,

  // 時段管理相關成功訊息
  SCHEDULE_SETTINGS_GET_SUCCESS: MESSAGES.SCHEDULE.SETTINGS_GET_SUCCESS,
  SCHEDULE_SETTINGS_UPDATE_SUCCESS: MESSAGES.SCHEDULE.SETTINGS_UPDATE_SUCCESS,
  SCHEDULE_CONFLICT_CHECK_SUCCESS: MESSAGES.SCHEDULE.CONFLICT_CHECK_SUCCESS,

  // 教師後台管理相關成功訊息
  TEACHER_DASHBOARD_SUCCESS: MESSAGES.TEACHER_DASHBOARD.DASHBOARD_SUCCESS,
  TEACHER_STATS_SUCCESS: MESSAGES.TEACHER_DASHBOARD.STATS_SUCCESS,
  TEACHER_PERFORMANCE_SUCCESS: MESSAGES.TEACHER_DASHBOARD.PERFORMANCE_SUCCESS,
  TEACHER_STUDENTS_LIST_SUCCESS: MESSAGES.TEACHER_DASHBOARD.STUDENTS_LIST_SUCCESS,
  TEACHER_STUDENT_DETAIL_SUCCESS: MESSAGES.TEACHER_DASHBOARD.STUDENT_DETAIL_SUCCESS,
  TEACHER_STUDENT_PURCHASES_SUCCESS: MESSAGES.TEACHER_DASHBOARD.STUDENT_PURCHASES_SUCCESS,
  TEACHER_STUDENT_RESERVATIONS_SUCCESS: MESSAGES.TEACHER_DASHBOARD.STUDENT_RESERVATIONS_SUCCESS,
  TEACHER_EARNINGS_SUCCESS: MESSAGES.TEACHER_DASHBOARD.EARNINGS_SUCCESS,
  TEACHER_SETTLEMENTS_SUCCESS: MESSAGES.TEACHER_DASHBOARD.SETTLEMENTS_SUCCESS,
  TEACHER_EARNINGS_STATS_SUCCESS: MESSAGES.TEACHER_DASHBOARD.EARNINGS_STATS_SUCCESS,
} as const

// 維持原有的 SuccessMessages 別名
export const SuccessMessages = SUCCESS

// === 向後相容性：ERROR_MESSAGES 結構 ===
// 維持與原始 ERROR_MESSAGES 完全相同的結構
export const ERROR_MESSAGES = {
  // 認證相關錯誤訊息
  AUTH: MESSAGES.AUTH,
  
  // 驗證相關錯誤訊息
  VALIDATION: MESSAGES.VALIDATION,
  
  // 業務邏輯錯誤訊息
  BUSINESS: MESSAGES.BUSINESS,
  
  // 系統錯誤訊息
  SYSTEM: MESSAGES.SYSTEM,
  
  // 成功訊息
  SUCCESS,
} as const

// === 型別定義 ===
export type MessageCategory = keyof typeof MESSAGES
export type AuthMessageKey = keyof typeof MESSAGES.AUTH
export type ValidationMessageKey = keyof typeof MESSAGES.VALIDATION
export type BusinessMessageKey = keyof typeof MESSAGES.BUSINESS
export type SystemMessageKey = keyof typeof MESSAGES.SYSTEM
export type WorkExperienceMessageKey = keyof typeof MESSAGES.WORK_EXPERIENCE
export type LearningExperienceMessageKey = keyof typeof MESSAGES.LEARNING_EXPERIENCE
export type CourseMessageKey = keyof typeof MESSAGES.COURSE
export type PriceOptionMessageKey = keyof typeof MESSAGES.PRICE_OPTION
export type VideoMessageKey = keyof typeof MESSAGES.VIDEO
export type CourseVideoMessageKey = keyof typeof MESSAGES.COURSE_VIDEO

// 便捷型別 - 向後相容
export type SuccessMessageKey = keyof typeof SUCCESS