/**
 * 教師相關常數定義
 */

// 驗證規則常數
export const TEACHER_VALIDATION = {
  NATIONALITY: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 50
  },
  INTRODUCTION: {
    MIN_LENGTH: 100,
    MAX_LENGTH: 1000
  }
} as const

// 業務錯誤碼
export const TEACHER_ERROR_CODES = {
  DUPLICATE_APPLICATION: 'DUPLICATE_APPLICATION',
  ROLE_FORBIDDEN: 'ROLE_FORBIDDEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
  TEACHER_NOT_APPROVED: 'TEACHER_NOT_APPROVED'
} as const

// 業務錯誤訊息
export const TEACHER_ERROR_MESSAGES = {
  [TEACHER_ERROR_CODES.DUPLICATE_APPLICATION]: '您已經有教師申請記錄',
  [TEACHER_ERROR_CODES.ROLE_FORBIDDEN]: '只有學生可以申請成為教師',
  [TEACHER_ERROR_CODES.ACCOUNT_INACTIVE]: '帳號狀態異常，無法申請',
  [TEACHER_ERROR_CODES.APPLICATION_NOT_FOUND]: '找不到教師申請記錄',
  [TEACHER_ERROR_CODES.APPLICATION_APPROVED]: '只能在待審核或已拒絕狀態下修改申請',
  [TEACHER_ERROR_CODES.USER_NOT_FOUND]: '使用者不存在',
  [TEACHER_ERROR_CODES.TEACHER_NOT_FOUND]: '找不到教師資料或尚未通過審核',
  [TEACHER_ERROR_CODES.TEACHER_NOT_APPROVED]: '找不到教師資料或尚未通過審核'
} as const

// HTTP 狀態碼映射
export const TEACHER_HTTP_STATUS = {
  [TEACHER_ERROR_CODES.DUPLICATE_APPLICATION]: 409,
  [TEACHER_ERROR_CODES.ROLE_FORBIDDEN]: 403,
  [TEACHER_ERROR_CODES.ACCOUNT_INACTIVE]: 403,
  [TEACHER_ERROR_CODES.APPLICATION_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.APPLICATION_APPROVED]: 400,
  [TEACHER_ERROR_CODES.USER_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.TEACHER_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.TEACHER_NOT_APPROVED]: 404
} as const