/**
 * 教師申請相關錯誤處理常數
 */

// 驗證規則常數
export const TEACHER_VALIDATION = {
  NATIONALITY: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 50
  },
  INTRODUCTION: {
    MIN_LENGTH: 100,
    MAX_LENGTH: 1000
  },
  COMPANY_NAME: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 200
  },
  WORKPLACE: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 200
  },
  JOB_CATEGORY: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 100
  },
  JOB_TITLE: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 100
  },
  SCHOOL_NAME: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 200
  },
  DEPARTMENT: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 200
  },
  DEGREE: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 50
  },
  VERIFYING_INSTITUTION: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 200
  },
  LICENSE_NAME: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 200
  },
  HOLDER_NAME: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 100
  },
  LICENSE_NUMBER: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 100
  },
  CATEGORY_ID: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 50
  },
  SUBJECT: {
    MIN_LENGTH: 1,
    MAX_LENGTH: 100
  }
} as const

// 業務錯誤碼
export const TEACHER_ERROR_CODES = {
  // 現有錯誤碼
  DUPLICATE_APPLICATION: 'DUPLICATE_APPLICATION',
  ROLE_FORBIDDEN: 'ROLE_FORBIDDEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
  TEACHER_NOT_APPROVED: 'TEACHER_NOT_APPROVED',
  
  // 重新提交申請相關錯誤
  CANNOT_RESUBMIT_APPLICATION: 'CANNOT_RESUBMIT_APPLICATION',
  INVALID_APPLICATION_STATUS: 'INVALID_APPLICATION_STATUS',
  
  // 工作經驗錯誤
  WORK_EXPERIENCE_NOT_FOUND: 'WORK_EXPERIENCE_NOT_FOUND',
  INVALID_WORK_PERIOD: 'INVALID_WORK_PERIOD',
  
  // 學習經歷錯誤
  LEARNING_EXPERIENCE_NOT_FOUND: 'LEARNING_EXPERIENCE_NOT_FOUND',
  INVALID_STUDY_PERIOD: 'INVALID_STUDY_PERIOD',
  CERTIFICATE_FILE_REQUIRED: 'CERTIFICATE_FILE_REQUIRED',
  
  // 證書錯誤
  CERTIFICATE_NOT_FOUND: 'CERTIFICATE_NOT_FOUND',
  CERTIFICATE_FILE_REQUIRED_FOR_CREATE: 'CERTIFICATE_FILE_REQUIRED_FOR_CREATE',
  
  // 時間管理錯誤
  INVALID_TIME_SLOT: 'INVALID_TIME_SLOT',
  TIME_CONFLICT: 'TIME_CONFLICT',
  INVALID_WEEKDAY: 'INVALID_WEEKDAY',
  
  // 檔案相關錯誤
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  
  // 權限相關錯誤
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  RESOURCE_NOT_OWNED: 'RESOURCE_NOT_OWNED'
} as const

// 業務錯誤訊息
export const TEACHER_ERROR_MESSAGES = {
  // 現有錯誤訊息
  [TEACHER_ERROR_CODES.DUPLICATE_APPLICATION]: '您已經有教師申請記錄',
  [TEACHER_ERROR_CODES.ROLE_FORBIDDEN]: '只有學生可以申請成為教師',
  [TEACHER_ERROR_CODES.ACCOUNT_INACTIVE]: '帳號狀態異常，無法申請',
  [TEACHER_ERROR_CODES.APPLICATION_NOT_FOUND]: '找不到教師申請記錄',
  [TEACHER_ERROR_CODES.APPLICATION_APPROVED]: '只能在待審核或已拒絕狀態下修改申請',
  [TEACHER_ERROR_CODES.USER_NOT_FOUND]: '使用者不存在',
  [TEACHER_ERROR_CODES.TEACHER_NOT_FOUND]: '找不到教師資料或尚未通過審核',
  [TEACHER_ERROR_CODES.TEACHER_NOT_APPROVED]: '找不到教師資料或尚未通過審核',
  
  // 重新提交申請相關訊息
  [TEACHER_ERROR_CODES.CANNOT_RESUBMIT_APPLICATION]: '此申請無法重新提交，請檢查申請狀態',
  [TEACHER_ERROR_CODES.INVALID_APPLICATION_STATUS]: '申請狀態無效',
  
  // 工作經驗訊息
  [TEACHER_ERROR_CODES.WORK_EXPERIENCE_NOT_FOUND]: '找不到指定的工作經驗記錄',
  [TEACHER_ERROR_CODES.INVALID_WORK_PERIOD]: '工作時間區間設定不正確',
  
  // 學習經歷訊息
  [TEACHER_ERROR_CODES.LEARNING_EXPERIENCE_NOT_FOUND]: '找不到指定的學習經歷記錄',
  [TEACHER_ERROR_CODES.INVALID_STUDY_PERIOD]: '學習時間區間設定不正確',
  [TEACHER_ERROR_CODES.CERTIFICATE_FILE_REQUIRED]: '學歷證明檔案為必要項目',
  
  // 證書訊息
  [TEACHER_ERROR_CODES.CERTIFICATE_NOT_FOUND]: '找不到指定的證書記錄',
  [TEACHER_ERROR_CODES.CERTIFICATE_FILE_REQUIRED_FOR_CREATE]: '新增證書時檔案為必要項目',
  
  // 時間管理訊息
  [TEACHER_ERROR_CODES.INVALID_TIME_SLOT]: '時間段格式不正確',
  [TEACHER_ERROR_CODES.TIME_CONFLICT]: '時間段存在衝突',
  [TEACHER_ERROR_CODES.INVALID_WEEKDAY]: '星期設定不正確（0-6）',
  
  // 檔案相關訊息
  [TEACHER_ERROR_CODES.FILE_TOO_LARGE]: '檔案大小超過5MB限制',
  [TEACHER_ERROR_CODES.UNSUPPORTED_FILE_TYPE]: '不支援的檔案格式，僅支援PDF、JPG、JPEG、PNG',
  [TEACHER_ERROR_CODES.FILE_UPLOAD_FAILED]: '檔案上傳失敗',
  
  // 權限相關訊息
  [TEACHER_ERROR_CODES.UNAUTHORIZED_ACCESS]: '無權存取此資源',
  [TEACHER_ERROR_CODES.RESOURCE_NOT_OWNED]: '您不是此資源的擁有者'
} as const

// HTTP 狀態碼映射
export const TEACHER_HTTP_STATUS = {
  // 現有狀態碼映射
  [TEACHER_ERROR_CODES.DUPLICATE_APPLICATION]: 409,
  [TEACHER_ERROR_CODES.ROLE_FORBIDDEN]: 403,
  [TEACHER_ERROR_CODES.ACCOUNT_INACTIVE]: 403,
  [TEACHER_ERROR_CODES.APPLICATION_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.APPLICATION_APPROVED]: 400,
  [TEACHER_ERROR_CODES.USER_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.TEACHER_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.TEACHER_NOT_APPROVED]: 404,
  
  // 新增狀態碼映射
  [TEACHER_ERROR_CODES.CANNOT_RESUBMIT_APPLICATION]: 400,
  [TEACHER_ERROR_CODES.INVALID_APPLICATION_STATUS]: 400,
  [TEACHER_ERROR_CODES.WORK_EXPERIENCE_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.INVALID_WORK_PERIOD]: 400,
  [TEACHER_ERROR_CODES.LEARNING_EXPERIENCE_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.INVALID_STUDY_PERIOD]: 400,
  [TEACHER_ERROR_CODES.CERTIFICATE_FILE_REQUIRED]: 400,
  [TEACHER_ERROR_CODES.CERTIFICATE_NOT_FOUND]: 404,
  [TEACHER_ERROR_CODES.CERTIFICATE_FILE_REQUIRED_FOR_CREATE]: 400,
  [TEACHER_ERROR_CODES.INVALID_TIME_SLOT]: 400,
  [TEACHER_ERROR_CODES.TIME_CONFLICT]: 409,
  [TEACHER_ERROR_CODES.INVALID_WEEKDAY]: 400,
  [TEACHER_ERROR_CODES.FILE_TOO_LARGE]: 413,
  [TEACHER_ERROR_CODES.UNSUPPORTED_FILE_TYPE]: 415,
  [TEACHER_ERROR_CODES.FILE_UPLOAD_FAILED]: 500,
  [TEACHER_ERROR_CODES.UNAUTHORIZED_ACCESS]: 403,
  [TEACHER_ERROR_CODES.RESOURCE_NOT_OWNED]: 403
} as const

// 成功訊息定義
export const TEACHER_SUCCESS_MESSAGES = {
  // 申請相關
  APPLICATION_CREATED: '教師申請已建立',
  APPLICATION_UPDATED: '申請資料更新成功',
  APPLICATION_RESUBMITTED: '申請已重新提交',
  APPLICATION_SUBMITTED: '教師申請已提交，等待審核',
  
  // 資料管理
  PROFILE_UPDATED: '教師資料更新成功',
  PROFILE_RETRIEVED: '取得教師資料成功',
  
  // 工作經驗
  WORK_EXPERIENCE_CREATED: '工作經驗已新增',
  WORK_EXPERIENCE_UPDATED: '工作經驗已更新',
  WORK_EXPERIENCE_DELETED: '工作經驗已刪除',
  WORK_EXPERIENCE_LIST_RETRIEVED: '取得工作經驗列表成功',
  
  // 學習經歷
  LEARNING_EXPERIENCE_CREATED: '學習經歷已新增',
  LEARNING_EXPERIENCE_UPDATED: '學習經歷已更新',
  LEARNING_EXPERIENCE_DELETED: '學習經歷已刪除',
  LEARNING_EXPERIENCE_LIST_RETRIEVED: '取得學習經歷列表成功',
  
  // 證書
  CERTIFICATE_CREATED: '證書已新增',
  CERTIFICATE_UPDATED: '證書已更新',
  CERTIFICATE_DELETED: '證書已刪除',
  CERTIFICATE_LIST_RETRIEVED: '取得證書列表成功',
  
  // 時間管理
  SCHEDULE_UPDATED: '時間設定已更新',
  SCHEDULE_RETRIEVED: '取得時間設定成功',
  
  // 檔案上傳
  FILE_UPLOADED: '檔案上傳成功'
} as const

// 支援的檔案類型
export const SUPPORTED_FILE_TYPES = {
  MIME_TYPES: [
    'application/pdf',
    'image/jpeg',
    'image/jpg', 
    'image/png'
  ],
  EXTENSIONS: [
    '.pdf',
    '.jpg',
    '.jpeg',
    '.png'
  ]
} as const

// 檔案大小限制（5MB）
export const FILE_SIZE_LIMIT = 5 * 1024 * 1024