export * from './handleErrorAsync.interface'
export * from './auth.interface'
export * from './teacher.interface'
export * from './validation.interface'
export * from './api.interface'
export * from './test.interface'
export * from './schedule.interface'
export * from './course.interface'